<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rowles.Morphogenesis.Optimisation</RootNamespace>
    <AssemblyName>Rowles.Morphogenesis.Evolution</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rowles.Evolution/Rowles.Evolution.csproj" />
    <ProjectReference Include="../Rowles.Morphogenesis/Rowles.Morphogenesis.csproj" />
  </ItemGroup>
</Project>
