<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rowles.Morphogenesis.Reference</RootNamespace>
    <AssemblyName>Rowles.Morphogenesis.Reference</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rowles.StrictMaths/Rowles.StrictMaths.csproj" />
  </ItemGroup>
</Project>
