<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Rowles.Morphogenesis</RootNamespace>
    <AssemblyName>Rowles.Morphogenesis</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rowles.StrictMaths/Rowles.StrictMaths.csproj" />
    <InternalsVisibleTo Include="Rowles.Morphogenesis.Tests" />
    <InternalsVisibleTo Include="Rowles.Morphogenesis.Benchmarks" />
  </ItemGroup>
</Project>
